apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bsoq7r33p-go 
  janus-idp.io/tekton: bsoq7r33p-go
  backstage.io/kubernetes-id: bsoq7r33p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bsoq7r33p-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  