apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bsoq7r33p-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bsoq7r33p-go 
  name: bsoq7r33p-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bsoq7r33p-go 
